# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

###### Default build via devtools::use_travis()

language: r
sudo: false
cache: packages

###### Custom Options

# Containers have 2 CPUs by default. Speed up the build by using both.
# c.f. https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system
env:
  global:
  - MAKEFLAGS="-j 2"
  - _R_CHECK_FORCE_SUGGESTS

jobs:
  include:
  - r: devel
  - r: release
  
