# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Generate Multinomial Random Variable
#' @description Sample a multinomial random variable for given probabilities.
#' @usage rmultinomial(ps)
#' @param ps A \code{vector} for the probability of each category.
#' @return A \code{vector} from a multinomial with probability ps.
#' @author Steven Andrew Culpepper
#'
rmultinomial <- function(ps) {
  .Call('_rRUM_rmultinomialcpp', PACKAGE = 'rRUM', ps)
}

#' @title Generate Dirichlet Random Variable
#' @description Sample a Dirichlet random variable.
#' @usage rDirichlet(deltas)
#' @param deltas A \code{vector} of Dirichlet parameters.
#' @return A \code{vector} from a Dirichlet.
#' @author Steven Andrew Culpepper
#'
rDirichlet <- function(deltas) {
  .Call('_rRUM_rDirichletcpp', PACKAGE = 'rRUM', deltas)
}

#' @title Generate data from the rRUM
#' @description Randomly generate response data according to the reduced Reparametrized Unified Model (rRUM).
#' @usage simrRUM(Q, rstar, pistar, alpha)
#' @param Q A \code{matrix} with J rows and K columns indicating which attributes are required to answer each of the items, where J represents the number of items and K the number of attributes.  An entry of 1 indicates attribute k is required to answer item j.  An entry of one indicates attribute k is not required.
#' @param rstar A \code{matrix} a matrix with J rows and K columns indicating the penalties for failing to have each of the required attributes, where J represents the number of items and K the number of attributes.  rstar and Q must share the same 0 entries.
#' @param pistar A \code{vector} of length J indicating the probabiliies of answering each item correctly for individuals who do not lack any required attribute, where J represents the number of items.
#' @param alpha A \code{matrix} with N rows and K columns indicating the subjects attribute acquisition, where N reperesnts the number of individuals and K the number of attributes.  An entry of 1 indicates individual i has attained attribute k.  An entry of 0 indicates the attribute has not been attained.
#' @return Y A \code{matrix} with N rows and J columns indicating the indviduals' responses to each of the items, where J represents the number of items.
#' @author Steven Andrew Culpepper
#'
simrRUM <- function(Q, rstar, pistar, alpha) {
  if(!all(dim(Q) == dim(rstar))) {
    stop("Q and rstar must have the same dimensionaltiy")
  }
  Q0 <- which(Q == 0)
  rstar0 <- which(rstar == 0)
  if(!(all(rstar0 %in% Q0) & all(Q0 %in% rstar0))) {
    stop("rstar and Q must have the same 0 entries")
  }
  if(length(pistar) != nrow(Q)) {
    stop("length(pistar) must be equal to nrow(Q)")
  }
  if(ncol(alpha) != ncol(Q)) {
    stop("alpha and Q must have the same number of columns")
  }
  if(!(all(rstar >= 0) & all(rstar <= 1) & all(pistar >= 0) & all(pistar <= 1))) {
    stop("all entries of pistar and rstar must be bound between 0 and 1")
  }
  N <- nrow(alpha)
  .Call('_rRUM_simrRUMcpp', PACKAGE = 'rRUM', N, Q, rstar, pistar, alpha)
}

#' @title Gibbs sampler to estimate the rRUM
#' @description Obtains samples from posterior distributon for the reduced Reparametrized Unified Model (rRUM).
#' @usage rRUM(Y, Q, chain_length = 10000L, as = 1, bs = 1, ag = 1, bg = 1, delta0 = rep(1, 2 ^ ncol(Q)))
#' @param Y A \code{matrix} with N rows and J columns, where N reperesnts the number of individuals and J the number of items.  Y indicates the indviduals' responses to each of the items.
#' @param Q A \code{matrix} with J rows and K columns indicating which attributes are required to answer each of the items.  An entry of 1 indicates attribute k is required to answer item j.  An entry of one indicates attribute k is not required.
#' @param chain_length A \code{numeric} indicating the number of iterations of Gibbs sampler to be run.  Default is set to 10000.
#' @param as A \code{numeric}, parameter for the prior distribution of pistar.  High values as encourage higher values of pistar and lower values of rstar.
#' @param bs A \code{numeric}, parameter for the prior distribution of pistar.  High values as encourage lower values of pistar and higher values of rstar.
#' @param ag A \code{numeric}, parameter for the prior distribution of rstar.  High values as encourage higher values of rstar.
#' @param bg A \code{numeric}, parameter for the prior distribution of pistar.  High values as encourage lower values of rstar.
#' @param delta0 A \code{vector}, parameters for the Dirichlet prior on pi.
#' @return PISTAR A \code{matrix} where each column represents one draw from the posterior distribution of pistar.
#' @return RSTAR A J x K x chain_length \code{array} where J reperesents the number of items, and K represents the number of attributes. Each slice represents one draw from the posterior distribution of rstar.
#' @return PI \code{matrix} where each column reperesents one draw from the posterior distribution of pi.
#' @return ALPHA An N x K x chain_length \code{array} where N reperesents the number of individuals, and K represents the number of attributes. Each slice represents one draw from the posterior distribution of alpha.
#' @author Steven Andrew Culpepper, Aaron Hudson
#'
rRUM_Gibbs <- function(Y, Q, chain_length = 10000L, as = 1, bs = 1, ag = 1, bg = 1, delta0 = rep(1, 2 ^ ncol(Q))) {
  if(nrow(Q) != ncol(Y)) {
    stop("Y must have as many rows as Q has columns")
  }
  if(length(as) != 1 | length(ag) != 1 | length(bs) != 1 | length(bg) != 1) {
    stop("as, ag, bs, and bg must all be numeric and of length 1")
  }
  if(length(delta0) != 2 ^ ncol(Q)) {
    stop("delta0 must be numeric of length 2 ^ ncol(Q)")
  }
  if(chain_length %% 1 != 0) {
    stop("chain_length must be an integer")
  }
  .Call('_rRUM_rRUM_Gibbscpp', PACKAGE = 'rRUM', Y, Q, delta0, chain_length, as, bs, ag, bg)
}

#' @title Mapping of Entries of Pi to Latent Attribute Classes
#' @description Obtains mapping of entries to pi to latent attribute classes.
#' @usage pi_reference(K)
#' @param K A \code{numeric}, denoting the number of attributes.
#' @return A \code{matrix}, where row c represents the latent class corresponding to entry c of pi
#' @author Steven Andrew Culpepper, Aaron Hudson
#'
pi_reference <- function(K) {
  biject.vector <- .Call('_rRUM_bijectionvectorcpp', PACKAGE = 'rRUM', K)
  As = as.matrix(expand.grid(rep(list(c(0,1)), K)))
  a = As%*%biject.vector
  As = As[a+1,]
  return(As)
}

